/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2019-06-29 13:36:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.index;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.5.10.1.jar", Long.valueOf(1558585065844L));
    _jspx_dependants.put("jar:file:/C:/Users/hp/Desktop/实验/Web应用实验/web应用课程设计/OnlineBookstore/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/ssh_book_mysql/WEB-INF/lib/struts2-core-2.5.10.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1488770942000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/preset.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/animate.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/owl.carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/owl.theme.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/responsive.css\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/layer.js\"></script>\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 头部导航 -->\r\n");
      out.write("        <header class=\"header-area\" style=\"position: fixed;width: 100%;\">\r\n");
      out.write("            <nav class=\"main-menu hidden-xs hidden-sm\">\r\n");
      out.write("                <ul class=\"menu-left pull-left\">\r\n");
      out.write("                    <li ");
      if (_jspx_meth_s_005fif_005f0(_jspx_page_context))
        return;
      out.write("><a href=\"index.action\">首页</a></li>\r\n");
      out.write("                    <li ");
      if (_jspx_meth_s_005fif_005f1(_jspx_page_context))
        return;
      out.write("><a href=\"about.action\">书店简介</a></li>\r\n");
      out.write("                    <li class=\"menu-has-children\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"new.jsp\">近期活动</a>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("                 \t\t\t<li><a href=\"special.jsp\">精品推荐</a>\r\n");
      out.write("                    \t\t<li><a href=\"new.jsp\">最新出版</a>\r\n");
      out.write("                    \t\t<li><a href=\"sale.jsp\">优惠促销</a>\r\n");
      out.write("                    \t</ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <!-- 中间logo -->\r\n");
      out.write("                <div class=\"pull-left logo-area\">\r\n");
      out.write("                    <a href=\"index.jsp\"><img src=\"images/logo.gif\" alt=\"Logo\" style=\"width: 100px;height: 60px;padding-top: 12px;margin-left: 30px;margin-right: 30px;\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <ul class=\"menu-right pull-left\">\r\n");
      out.write("                    <li><a href=\"cart.action\">购物车</a></li>\r\n");
      out.write("                    <li><a href=\"order.action\">我的订单</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("\r\n");
      out.write("            <!-- 最右边栏 -->\r\n");
      out.write("            <ul class=\"pull-right search-cart\">\r\n");
      out.write("            \t<li style=\"float: right; margin-left: 30px;\">\r\n");
      out.write("\t\t\t\t\t<form action=\"search.action\" method=\"post\" id=\"form_search\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0);\" onclick=\"$('#form_search').submit()\" style=\"float: right;margin-left:0\">搜索</a>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"searchName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"输入图书名称\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<!-- <form action=\"search.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"search\" placeholder=\"请输入图书名称\" size=\"10\"/>\r\n");
      out.write("\t\t\t\t\t\t&nbsp;&nbsp;<input type=\"submit\" value=\"搜索\" style=\"float: right;margin-left:0\">\r\n");
      out.write("\t\t\t\t\t</form> -->\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"menu-has-children\">\r\n");
      out.write("\t\t\t\t\t<a href=\"login.jsp\">用户</a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"login.jsp\">用户登陆</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"register.jsp\">用户注册</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"logout.action\">注销用户</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"../admin/login.jsp\" target=\"_blank\">后台管理</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("                \r\n");
      out.write("                <li class=\"menu-has-children\">\r\n");
      out.write("                    <a href=\"#\">语言栏</a>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">En</a>\r\n");
      out.write("                        <li><a href=\"#\">Ch</a>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li> \r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"clearfix\"></div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- head nav end -->\r\n");
      out.write("        <div class=\"top_line_color\">\r\n");
      out.write("        <p style=\"border:6px solid #8b0000;\"></p>\r\n");
      out.write("        <!-- Slider Area Start -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".second-animation{\r\n");
      out.write("\tpadding-left:120px;\r\n");
      out.write("}\r\n");
      out.write(".bordered-button{\r\n");
      out.write("\tmargin-left:150px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("        <section class=\"slider-area\">\r\n");
      out.write("            <div id=\"home-one-crousel\" class=\"carousel slide\">\r\n");
      out.write("                <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("                    <div class=\"item active\" style=\"background-image: url(../images/slider/slider01.gif);background-size: 100% auto\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-12 col-xs-12\">\r\n");
      out.write("                                    <div class=\"slider-content text-left\">\r\n");
      out.write("                                        <h3 class=\"second-animation\">林海书店</h3>\r\n");
      out.write("                                        <a href=\"about.jsp\" class=\"bordered-button fourth-animation\">DETAILS<i class=\"fa fa-long-arrow-right\"></i></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"slider-overlay\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"item\" style=\"background-image: url(../images/slider/slider02.jpg);background-size: 100% auto\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-12 col-xs-12\">\r\n");
      out.write("                                    <div class=\"slider-content text-left\">\r\n");
      out.write("                                    <h3 class=\"second-animation\">LinHai</h3>\r\n");
      out.write("                                        <a href=\"about.jsp\" class=\"bordered-button fourth-animation\">DETAILS<i class=\"fa fa-long-arrow-right\"></i></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"slider-overlay\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"item\" style=\"background-image: url(../images/slider/slider03.jpg);background-size: 100% auto\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-12 col-xs-12\">\r\n");
      out.write("                                    <div class=\"slider-content text-left\">\r\n");
      out.write("                                        <h3 class=\"second-animation\">百年之作</h3>\r\n");
      out.write("                                        <a href=\"new.jsp\" class=\"bordered-button fourth-animation\">DETAILS<i class=\"fa fa-long-arrow-right\"></i></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"slider-overlay\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"item\" style=\"background-image: url(../images/slider/slider04.jpg);background-size: 100% auto\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-12 col-xs-12\">\r\n");
      out.write("                                    <div class=\"slider-content text-left\">\r\n");
      out.write("                                        <h3 class=\"second-animation\">审美</h3>\r\n");
      out.write("                                        <a href=\"sale.jsp\" class=\"bordered-button fourth-animation\">DETAILS<i class=\"fa fa-long-arrow-right\"></i></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"slider-overlay\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"item\" style=\"background-image: url(../images/slider/slider05.jpg);background-size: 100% auto\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-12 col-xs-12\">\r\n");
      out.write("                                    <div class=\"slider-content text-left\">\r\n");
      out.write("                                        <h3 class=\"second-animation\">Book</h3>\r\n");
      out.write("                                        <a href=\"sale.jsp\" class=\"bordered-button fourth-animation\">DETAILS<i class=\"fa fa-long-arrow-right\"></i></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"slider-overlay\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"item\" style=\"background-image: url(../images/slider/slider06.gif);background-size: 100% auto\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-12 col-xs-12\">\r\n");
      out.write("                                    <div class=\"slider-content text-left\">\r\n");
      out.write("                                        <h3 class=\"second-animation\">读一本好书</h3>\r\n");
      out.write("                                        <a href=\"new.jsp\" class=\"bordered-button fourth-animation\">DETAILS<i class=\"fa fa-long-arrow-right\"></i></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"slider-overlay\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- control button -->\r\n");
      out.write("                <a class=\"left carousel-control\" href=\"#home-one-crousel\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("                    <i class=\"fa fa-angle-left\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"right carousel-control\" href=\"#home-one-crousel\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("                    <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Slider Area End -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f0 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    boolean _jspx_th_s_005fif_005f0_reused = false;
    try {
      _jspx_th_s_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fif_005f0.setParent(null);
      // /index/header.jsp(26,24) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fif_005f0.setTest("flag==1");
      int _jspx_eval_s_005fif_005f0 = _jspx_th_s_005fif_005f0.doStartTag();
      if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fif_005f0);
        }
        do {
          out.write("class=\"selected\"");
          int evalDoAfterBody = _jspx_th_s_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fif_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f0);
      _jspx_th_s_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:if
    org.apache.struts2.views.jsp.IfTag _jspx_th_s_005fif_005f1 = (org.apache.struts2.views.jsp.IfTag) _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.get(org.apache.struts2.views.jsp.IfTag.class);
    boolean _jspx_th_s_005fif_005f1_reused = false;
    try {
      _jspx_th_s_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005fif_005f1.setParent(null);
      // /index/header.jsp(27,24) name = test type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fif_005f1.setTest("flag==1");
      int _jspx_eval_s_005fif_005f1 = _jspx_th_s_005fif_005f1.doStartTag();
      if (_jspx_eval_s_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_s_005fif_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_s_005fif_005f1);
        }
        do {
          out.write("class=\"selected\"");
          int evalDoAfterBody = _jspx_th_s_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_s_005fif_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_s_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fs_005fif_0026_005ftest.reuse(_jspx_th_s_005fif_005f1);
      _jspx_th_s_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_s_005fif_005f1_reused);
    }
    return false;
  }
}
