/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2019-06-07 06:28:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.index;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/tset.css\"/>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- Latest News Area Start -->\r\n");
      out.write("        <section class=\"latest-news\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-12 col-xs-12 text-center\">\r\n");
      out.write("                        <a href=\"event.html\">\r\n");
      out.write("                            <h2 class=\"section-title\">图片<span>新闻</span></h2>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-md-6 col-xs-12 col-sm-6\">\r\n");
      out.write("                        <div class=\"news-wrap\">\r\n");
      out.write("                            <div class=\"news-img\">\r\n");
      out.write("                                <div class=\"news-date\">\r\n");
      out.write("                                    <p>2019/4/29</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img src=\"../picture/9.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <h3><a href=\"#\">我校举行第三十届“青春杯”五四火炬接力赛 </a></h3><p>\r\n");
      out.write("                                4月29日下午，学校举行第三十届“青春杯”五四火炬接力赛，纪念中华人民共和国成立70周年、五四运动100周年。副校长陈鹰，副校长陈杰，校党委委员、组织部部长郑春晔，校党委委员、学校办公室主任金晓明出席活动。学校各职能部门负责人，各学院党委、学生工作负责人和校友代表参加了活动，逾千名师生参与本...\r\n");
      out.write("                            </p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-md-6 col-xs-12 col-sm-6\">\r\n");
      out.write("                        <div class=\"thumbnail-news\">\r\n");
      out.write("                            <div class=\"news-img pull-left\">\r\n");
      out.write("                                <div class=\"news-date\">\r\n");
      out.write("                                    <p>2019/4/25</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img src=\"../picture/6.jpg\" alt=\"\"></div><div class=\"small-news pull-left\"><h4>\r\n");
      out.write("                                <a href=\"#\">我校与奥地利IMC克雷姆斯应用科技大学签署合作备忘录</a></h4><p>\r\n");
      out.write("                                    4月25日下午，由浙江省贸促会和奥地利驻上海总领事馆共同主办的“浙江省－下奥地利州商务论坛”在杭举行。奥地利总理塞巴斯蒂安·库尔茨、浙江省副省长朱从玖、下奥地利州州长约翰娜·米克尔-莱特纳等出席论坛并致辞，中国驻奥地利大使李晓驷、奥地利驻华大使石迪福以及中奥两国工商界嘉宾、企业家共300多人...\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"clearfix\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"thumbnail-news\">\r\n");
      out.write("                            <div class=\"news-img pull-left\">\r\n");
      out.write("                                <div class=\"news-date\">\r\n");
      out.write("                                    <p>2019/4/28</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img src=\"../picture/6.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"small-news pull-left\">\r\n");
      out.write("                                <h4><a href=\"#\">省科协与我校共同举办“向太空去·黑洞捕捉科幻季”科普派对活动 </a></h4><p>\r\n");
      out.write("                                    4月28日下午，“向太空去·黑洞捕捉科幻季”科普派对活动在省科协大楼举行。本次科普派对活动由浙江省科学技术协会和我校主办，浙江省科技馆、我校理学院、腾讯大浙网等负责承办，我校理论物与宇宙学研究所、融媒体、科学24小时杂志社协办。省科协党组成员、副主席陆锦，省科协科普部部长汪光年，《科学24小...\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"clearfix\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"thumbnail-news\">\r\n");
      out.write("                            <div class=\"news-img pull-left\">\r\n");
      out.write("                                <div class=\"news-date\">\r\n");
      out.write("                                    <p>2019/4/27</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img src=\"../picture/6.jpg\" alt=\"\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"small-news pull-left\">\r\n");
      out.write("                                <h4><a href=\"#\">\r\n");
      out.write("                                    中国住房和房地产研究院专家顾问委员会第一次会议暨学术研讨会在我校召开</a></h4><p>\r\n");
      out.write("                                    4月27日，中国住房和房地产研究院专家顾问委员会第一次会议暨学术研讨会在我校召开。住房和城乡建设部党组成员、副部长倪虹，浙江省住房和城乡建设厅党组成员、副厅长张奕，学校党委书记蔡袁强、副校长虞晓芬出席会议。参加会议的还有住建部相关司局、省住建厅相关处室负责人，研究院专家顾问委员会委员。&nb...\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"clearfix\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Latest News Area End -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
