/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.14
 * Generated at: 2019-06-27 11:15:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class left_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.5.10.1.jar", Long.valueOf(1558585065844L));
    _jspx_dependants.put("jar:file:/C:/Users/hp/Desktop/实验/Web应用实验/web应用课程设计/OnlineBookstore/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/ssh_book_mysql/WEB-INF/lib/struts2-core-2.5.10.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1488770942000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("html, body{\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tmargin: 0px 0px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("dl,ul,li{list-style:none;}\r\n");
      out.write("a{color:#000;}\r\n");
      out.write("a:link,a:visited,a:active,a:hover{text-decoration:none;}\r\n");
      out.write(".meun_div{width:110px;height:auto;border-top:0;background:#fff;padding-top:10px;font-size:14px;}\r\n");
      out.write(".meun_top{width:80px;height:27px;line-height:27px;padding-left:20px;}\r\n");
      out.write(".meun_img{float:left;width:7px;height:27px;background:url(images/menu_1.gif) no-repeat;}\r\n");
      out.write(".meun_box ul{margin:0;padding:0 5px 0 19px;font-size:12px;}\r\n");
      out.write(".meun_box li{width:auto;height:20px;line-height:20px;margin:3px 0;padding-left:2px;}\r\n");
      out.write(".none_box {display:block;}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/JavaScript\"> \r\n");
      out.write("var $=function(id) {\r\n");
      out.write("   return document.getElementById(id);\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("//显示子菜单\r\n");
      out.write("function show_menu_box(num){\r\n");
      out.write("\tif($('box'+num)){   \r\n");
      out.write("\t\tif($('box'+num).style.display=='none'){\r\n");
      out.write("\t\t\t$('box'+num).style.display='block';\r\n");
      out.write("\t\t\t$('img'+num).style.background='url(images/menu_2.gif)';\r\n");
      out.write("\t\t}else {\r\n");
      out.write("\t\t\t$('box'+num).style.display='none';\r\n");
      out.write("\t\t\t$('img'+num).style.background='url(images/menu_1.gif)';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<table width=\"173\" height=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"table-layout:fixed;\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"169\" valign=\"top\">\r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t\t<td height=\"20\" background=\"images/main_11.gif\">&nbsp;</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div class=\"meun_div\" align=\"center\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"meun_top\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"img1\" class=\"meun_img\"></div>\r\n");
      out.write("\t\t\t\t\t\t<a onclick=\"show_menu_box(1)\" href=\"javascript:;\">订单管理</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"meun_box none_box\" id=\"box1\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"indentList.action?status=1\"  target=\"rightFrame\">&middot;未处理</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"indentList.action?status=2\"  target=\"rightFrame\">&middot;已处理</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"meun_top\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"img2\" class=\"meun_img\"></div>\r\n");
      out.write("\t\t\t\t\t\t<a onclick=\"show_menu_box(2)\" href=\"javascript:;\">顾客管理</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"meun_box none_box\" id=\"box2\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"userList.action\"  target=\"rightFrame\">&middot;顾客列表</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"pages/user-add.jsp\"  target=\"rightFrame\">&middot;添加顾客</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"meun_top\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"img3\" class=\"meun_img\"></div>\r\n");
      out.write("\t\t\t\t\t\t<a onclick=\"show_menu_box(3)\" href=\"javascript:;\">图书管理</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"meun_box none_box\" id=\"box3\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"bookList.action\"  target=\"rightFrame\">&middot;图书列表</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"bookList.action?status=1\"  target=\"rightFrame\">&middot;推荐列表</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"bookList.action?status=2\"  target=\"rightFrame\">&middot;最新列表</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"bookList.action?status=3\"  target=\"rightFrame\">&middot;促销列表</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"bookAd.action\"  target=\"rightFrame\">&middot;添加图书</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"meun_top\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"img4\" class=\"meun_img\"></div>\r\n");
      out.write("\t\t\t\t\t\t<a onclick=\"show_menu_box(4)\" href=\"javascript:;\">类目管理</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"meun_box none_box\" id=\"box4\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"categoryList.action\"  target=\"rightFrame\">&middot;类目列表</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"pages/category-add.jsp\"  target=\"rightFrame\">&middot;添加类目</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"meun_top\">\r\n");
      out.write("\t\t\t\t\t\t<div id=\"img5\" class=\"meun_img\"></div>\r\n");
      out.write("\t\t\t\t\t\t<a onclick=\"show_menu_box(5)\" href=\"javascript:;\">用户管理</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"meun_box none_box\" id=\"box5\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"adminList.action\"  target=\"rightFrame\">&middot;用户列表</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"pages/admin-add.jsp\"  target=\"rightFrame\">&middot;添加用户</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
